version: "3.7"
services:
  mysql:
    container_name: sf5_mysql
    image: mysql:5.7
    ports: ["3306:3306"]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    container_name: sf5_php
    build: ./docker/php
    ports: ["9000:9001"]
    links:
      - mysql
    volumes:
      - ./symfony/:/var/www/symfony:cached
  nginx:
    container_name: sf5_nginx
    build: ./docker/nginx
    ports: ["80:80"]
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony/:/var/www/symfony:cached
  node:
    image: node:13-alpine
    working_dir: /var/www/react
    volumes:
      - ./react:/var/www/react
      - ./react:/bindmount:rw
    ports:
      - "8080:8080"
