api_home:
    path: /api
    controller: App\Controller\DefaultController::index
    
api_todos:
  path: /api/todos
  controller: App\Controller\TodoController::list
  
app:
  path: /{page}/{subpage}
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: 'base.html.twig'
    page: ''
    subpage: ''
  requirements:
    page: '^(?!api).+'
